
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exe_builder:

      runs-on: windows-latest


      steps:

        - name: Send greeting
          run: echo "Hello World!"
        - uses: actions/checkout@v3
        - name: install pyinstaller
          run: pip install pyinstaller
        - name: use pyinstaller
          run: |
            pyinstaller --onefile main.py
            echo "OK"
            dir
        - name: Path exe
          uses: actions/upload-artifact@v3
          with:
            name: Path to exe
            path: |
              main.spec
        - name: go next
          run: |
            cd dist
            dir
        - name: Exe in
          uses: actions/upload-artifact@v3
          with:
            name: Exe
            path: |
              main.exe
              D:\a\DevOps-lab2\DevOps-lab2\dist\main.exe

  Upload_artifacts:
      needs: exe_builder
      runs-on: ubuntu-latest

      steps:
        - name: Add artifact
          uses: actions/download-artifact@v3
        - name: Check
          run: ls
        - name: upload to google drive
          uses: adityak74/google-drive-upload-git-action@main
          with:
            credentials: ${{ secrets.CREDENTIALS }}
            filename: Exe/dist/*
            folderId: ${{ secrets.FOLDERID }}
            overwrite: "true"
  flake8_py3:
        runs-on: ubuntu-latest
    
        steps:
          - name: Check code
            uses: actions/checkout@v3
          - name: Install styleguide
            run: pip install wemake-python-styleguide
          - name: use styleguide
            continue-on-error: true
            run: |
              flake8 main.py
              echo "OK"
              echo "https://wemake-python-styleguide.rtfd.io/en/0.18.0/pages/usage/violations/" > res.txt
          - name: add https artifact
            uses: actions/upload-artifact@v3
            with:
              name: link
              path: |
                res.txt
          - name: Check if 'Lint with flake8' step failed
            if: steps.flake8.outcome != 'success'
            run: |
              echo "flake8 fails"
              echo "Main flow is end!"
              exit 0
