
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exe_builder:

      runs-on: windows-latest


      steps:

        - name: Send greeting
          run: echo "Hello World!"
        - uses: actions/checkout@v3
        - name: install pyinstaller
          run: pip install pyinstaller
        - name: use pyinstaller
          run: |
            pyinstaller --onefile main.py
            echo "OK"
            dir
        - name: Path exe
          uses: actions/upload-artifact@v3
          with:
            name: Path to exe
            path: |
              main.spec
        - name: go next
          run: |
            cd dist
            dir
        - name: Exe in
          uses: actions/upload-artifact@v3
          with:
            name: Exe
            path: |
              main.exe
              D:\a\DevOps-lab2\DevOps-lab2\dist\main.exe

  Upload_artifacts:
      needs: exe_builder
      runs-on: ubuntu-latest

      steps:
        - name: Add artifact
          uses: actions/download-artifact@v3
        - name: Check
          run: ls
        - name: upload to google drive
          uses: adityak74/google-drive-upload-git-action@main
          with:
            credentials: ${{ secrets.CREDENTIALS }}
            filename: Exe/dist/*
            folderId: ${{ secrets.FOLDERID }}
            overwrite: "true"
  code_state:
      needs: exe_builder
      name: Python Lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: Check
          run: ls
        - name: Run flake8
          uses: julianwachholz/flake8-action@v2
          with:
            checkName: "Python Lint"
            path: main.py
            plugins: flake8-spellcheck
            config: flake8.ini
        - name: Checkv2
          run: ls
